version: "3"
services:
  alerts:
    image: imauld/alerts:app-0.1.3
    ports:
      - "8081:8081"
    command: "./alerts-svc"
    links:
      - localstack
    environment:
      - "AWS_ACCESS_KEY_ID=foo"
      - "AWS_SECRET_ACCESS_KEY=bar"
  localstack:
    image: atlassianlabs/localstack:0.4.3
    ports:
      - "4567-4581:4567-4581"
    environment:
      - "DATA_DIR=/tmp/localstack-alerts/data"
    volumes:
      - "localstack_data:/tmp/localstack-alerts"
volumes:
  localstack_data:

