---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  labels:
    app: alerts
  name: alerts
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alerts
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: alerts
    spec:
      containers:
      - name: alerts
        image: imauld/alerts:app-0.1.2
        imagePullPolicy: IfNotPresent
        command: 
        - "./alerts-svc"
        ports:
        - containerPort: 8081
      dnsPolicy: ClusterFirst
      restartPolicy: Always
---
kind: Service
apiVersion: v1
metadata:
  name: alerts
spec:
  ports:
    - name: grpc
      port: 8081
      targetPort: 8081
  selector:
    app: alerts
  type: NodePort
